### ISSUE TITLE
Use library without npm install

### ISSUE THREAD

**Issue by ngreco** [tulip/multivariate-normal-js#1]
Is there a way to use this library without npm install? I can't seem to figure it out.

Things I have tried:
`var MultivariateNormal = require(".js/multivariate-normal.min.js")`
`var MultivariateNormal = require(".js/multivariate-normal.min.js").default`
`<script src="js/multivariate-normal.min.js"></script>`

None of these seem to give me access to MultivariateNormal for use.
I am trying to use this with AngularJS, and maybe that's the problem...

**Comment by benweissmann** [comment]
Looks like there was an issue with the way I had set up the browserify build. Grab the latest copy from the `dist` folder and you should be able to to access the global `window.MultivariateNormal.default`.
